<?php

return [
	'home' => [
		'home' => 'home',
		'search_by_category' => 'search_by_category',
		'product' => 'product',
		'fetch_cart_ajax' => 'fetch_cart_ajax',
		'add_product_ajax' => 'add_product_ajax',
		'remove_product_ajax' => 'remove_product_ajax',
	],
	'auth' => [
		'sign_in' => 'sign_in',
		'logout' => 'logout',
		'sign_in_validation' => 'sign_in_validation',
		'sign_up_validation' => 'sign_up_validation',
	],
	'dashboard' => [
		'home' => 'home',
		'create_operator' => 'create_operator',
		'fetch_country_states' => 'fetch_country_states',
		'fetch_state_cities' => 'fetch_state_cities',
		'add_operator' => 'add_operator',
		'edit_operator' => 'edit_operator',
		'change_operator_status' => 'change_operator_status',
		'create_user' => 'create_user',
		'add_user' => 'add_user',
		'edit_user' => 'edit_user',
		'create_category' => 'create_category',
		'add_category_validation' => 'add_category_validation',
		'operators_list' => 'operators_list',
		'users_list' => 'users_list',
		'create_product' => 'create_product',
		'edit_product' => 'edit_product',
		'edit_product_validation' => 'edit_product_validation',
		'add_product' => 'add_product',
		'products_list' => 'products_list',
		'products_categories' => 'products_categories',
		'aproducts_list' => 'aproducts_list',
		'product' => 'product',
		'logout' => 'logout',
	],
];